Install Packages Step: Add Install Packages Step to install the application binaries
GoogleCloudPlatform/cos-customizer pull request #76
Opened 2021-05-17 15:23 UTC by vteratipally

Add Install Packages step to install the application binaries ( using Installer ) with the input below by installing the Anthos installer. 
* pkgspec-dir ( Path to Package specification files in YAML format )
* work-dir ( Temporary workspace dir )

2021-05-17 17:06 UTC, rkolchmeyer requested changes
Can you also add documentation to the README?

2021-05-17 17:06 UTC, rkolchmeyer commented on testing/install_packages_test/install_packages_test.yaml
> +# Copyright 2021 Google LLC
nit: can you put this file in the top level of the testing/ directory? Otherwise run_tests.sh won't run the test.

2021-05-17 17:06 UTC, rkolchmeyer commented on testing/install_packages_test/install_packages_test.yaml
> +         '-timeout=5m']
Would it make sense to add a step at the end to validate the preloaded contents of the result image? See smoke_test.yaml for an example.

2021-05-17 17:06 UTC, rkolchmeyer commented on src/pkg/provisioner/config.go
> +	case "InstallPackages":
Can you add documentation for this new step in `type Config struct`?

2021-05-17 17:06 UTC, rkolchmeyer commented on src/pkg/provisioner/install_packages_step.go
> +	}
Is the intent to install the anthos-installer persistently on the system (i.e. make it available at runtime)? If so, it would be good to clarify that in the InstallPackageStep documentation.

2021-05-17 17:06 UTC, rkolchmeyer commented on src/pkg/provisioner/install_packages_step.go
> +	defer gcsClient.Close()
Instead of initializing a client here, would it make sense to inject it as a dependency? The current implementation prevents unit tests from being written.

IMO the best way to do this might be to:
- initialize the client in the Run and Resume subcommands (or maybe in main())
- Update the `step` interface such that `run()` has an additional `struct` input, that includes all client-like dependencies (e.g. GCS client)
- Pipe the client through provisioner.go to make it available here

Also, it would be better to pipe through the context as an argument than to always use context.Background().

2021-05-17 17:06 UTC, rkolchmeyer commented on src/pkg/provisioner/install_packages_step.go
> +func (ip *InstallPackagesStep) runInstaller(buildContext string) error {
In order for `CheckClose` to work properly, you need to have a named return value for the error, e.g. `(err error)`

2021-05-17 17:06 UTC, rkolchmeyer commented on src/pkg/provisioner/install_packages_step.go
> +	return nil
nit: this can be replaced with `return utils.RunCommand(...)`

2021-05-17 17:06 UTC, rkolchmeyer commented on src/pkg/provisioner/install_packages_step.go
> +		ip.AnthosInstallerVersion)
nit: this can fit on one line

2021-05-17 17:06 UTC, rkolchmeyer commented on src/cmd/cos_customizer/install_packages.go
> +	f.StringVar(&ip.TopWorkDir, "work-dir", "", "Path to the temporary working directory.")
Is there a specific reason why this can't be handled internally to cos-customizer? cos-customizer can pick a temporary working directory and clean it up when provisioning is complete.

2021-05-17 17:06 UTC, rkolchmeyer commented on src/cmd/cos_customizer/install_packages.go
> +	return "Installs the packages."
Can you provide a bit more detail here? Maybe something like:

"Installs packages specified by pkgspec files. See <url> for the format of pkgspec files."

2021-05-18 04:13 UTC, vteratipally commented on testing/install_packages_test/install_packages_test.yaml
> +# Copyright 2021 Google LLC
Moved to the top level directory testing/

2021-05-18 04:14 UTC, vteratipally commented on testing/install_packages_test/install_packages_test.yaml
> +         '-timeout=5m']
added a testing/install_packages_step/preload.cfg to verify the files installed.

2021-05-18 04:15 UTC, vteratipally commented on src/pkg/provisioner/install_packages_step.go
> +	}
No, anthos-installer has to be removed from the system. As discussed offline moved the working dir to the runState.dir

2021-05-18 04:16 UTC, vteratipally commented on src/pkg/provisioner/install_packages_step.go
> +	defer gcsClient.Close()
Tried to add type stepDeps config {} holding the reference to the storage client and tried to pass on the context in the run method as a separate argument.

2021-05-18 04:16 UTC, vteratipally commented on src/pkg/provisioner/install_packages_step.go
> +func (ip *InstallPackagesStep) runInstaller(buildContext string) error {
Changed the function.

2021-05-18 04:17 UTC, vteratipally commented on src/cmd/cos_customizer/install_packages.go
> +	f.StringVar(&ip.TopWorkDir, "work-dir", "", "Path to the temporary working directory.")
If cos-customizer can handle this, then it is not required. Removed the input argument.

2021-05-18 21:42 UTC, rkolchmeyer approved these changes

2021-05-18 22:58 UTC, merged